# Generated by Django 4.1 on 2023-03-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_title_seo',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название в поиске'),
        ),
    ]
