# Generated by Django 4.1 on 2023-03-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='title_seo',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название в поиске'),
        ),
    ]
